apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: Lokesh101090/discovery-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              value: "6001"
          ports:
            - containerPort: 6001

---

apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001

---

#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: discovery-ingress
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: discovery.local
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: discovery-service
#                port:
#                  number: 5001